### ISSUE TITLE
Deriving a struct that has a reference to another derived struct

### ISSUE THREAD

**Issue by dzervas** [avl/savefile#18]
Hello, I want to have a reference to another derived struct. For example

```rust
#[derive(Savefile)]
pub struct A {
  pub hello: String,
}

#[derive(Savefile)]
pub struct B<'a> {
  pub world: &'a A,
}
```

What I get is ```the trait `savefile::Deserialize<'_>` is not implemented for `&'a LedPattern``` and the same error for the rest of the required traits.

Any pointers?

**Comment by avl** [comment]
Hello, and thanks for getting in touch!

Unfortunately Savefile does not support serializing items which contain references. I should probably have added a + 'static bound to make this more explicit.

This is an interesting point you're bringing up.

I can see why you'd want to be able to use Savefile in this case. But it seems really hard to fix Savefile so that this would work.

The notation B<'a> means that each instance of B contains a reference to something with lifetime 'a. When deserializing an instance of B, Savefile would have to place the 'world'-object at a location with lifetime 'a. But, when deserialization starts, there is no instance of B available, and thus there is no lifetime 'a either. This means it's hard for Savefile to know where 'world' (in this example) should be placed in memory. It might be solvable to simply allocate 'world' on the heap and leak it. But it would be a strange solution. The idea of using something like B<'a> is that each instance of B has a reference to some other object, and that this reference is known at compile time. I don't see a way to recreate this after deserialization.

A code example

```rust

// Serialization
let my_a = A { hello: "Hello".to_string() };

let my_b = B { world: &a }; //my_b now has a reference to my_a.
save_file("save.bin",0,my_b).unwrap();

// Deserialization ?

let my_b : B = load_file("save.bin",0).unwrap(); //which A does my_b reference??

```

**Comment by dzervas** [comment]
wow, yea I didn't think all of this. And indeed there's no "ok" way of doing it. Weird...
Also I ended up not requiring it as Serde does not support this either (this should be a good enough indicator that it can't be done).

Thank you for your time though! Nice project!
