### ISSUE TITLE
Async IO support

### ISSUE THREAD

**Issue by PonasKovas** [avl/savefile#21]
Would it be in scope for this project?

**Comment by PonasKovas** [comment]
Well, in my specific case I would want to use the savefile functionality
from an async context, just writing to regular files, but since it can
block, it would be better for savefile to be async too.

I don't have much experience in this stuff, but from what I've seen in
other libraries, you probably could make an `async` feature that would
conditionally compile `AsyncSerialize` and `AsyncDeserialize` traits,
making them optional.

So most users would use the library as it is now, without any changes, and
those who need async functionality will just enable the `async` feature and
use the async counterparts.

**Comment by PonasKovas** [comment]
For example you could look at how [flate2-rs](
https://docs.rs/flate2/1.0.20/flate2/] does it.

**Comment by avl** [comment]
Hmm, if you are writing to regular files, are you sure you really need async? In almost all cases, operating system level write caching will make it so that your writes never actually block.

When reading, I guess async could be of some value if you have a really slow disk and you have other things you could use the CPU for when waiting for the disk. However, this requires that the application is actually built to take advantage of these spare CPU cycles. In many cases I bet it would be just as easy to just use a separate thread. But of course I don't know your application, so I may be missing something :-) .

I looked quickly at flate2. As I understand it, their approach is that they simply gracefully handle ErrorKind::WouldBlock, and allow operation to resume. This approach would not be easy to adapt to the needs of the Savefile crate, since it's impossible for the savefile infrastructure to know what kind of state a particular user-implementation of Serialize or Deserialize might have.

I'm afraid I still don't see a good way to implement async for Savefile. I'm open to being convinced otherwise, though :-).

That said, I urge you to do some benchmarks of the non-async write-performance of savefile in your application. I think you may find that it is not actually blocking at all when writing to disk.

**Comment by PonasKovas** [comment]
I guess you're right. I completely forgot that the OS does caching haha. I
can hardly imagine a use case where Savefile would be needed on network io,
so I guess there isn't really a point in making it async.

Thanks, I'd close the issue, but I'm on my phone right now, so feel free to
do so.

**Comment by avl** [comment]
Thanks for bringing up the question! And thanks for the PR adding Cow-support.
