### ISSUE TITLE
Saving external structs

### ISSUE THREAD

**Issue by chungwong** [avl/savefile#27]
Given
```rs
#[derive(Clone, Debug, Default, Savefile)]
enum ControAction {
  ..
}

#[derive(Clone, Debug, Default, Savefile)]
struct ControllerConfig {
  input_map: InputMap<ControAction>
  // input_map: Vec<KeyCode, ControlAction>
}

// Where
// KeyCode is from https://docs.rs/bevy/latest/bevy/input/keyboard/enum.KeyCode.html
// InputMap is from https://docs.rs/leafwing-input-manager/0.5.2/leafwing_input_manager/input_map/struct.InputMap.html
```
I couldn't find a way to save structs which invole external structs and got various erros from my attempts.

```bash
# for  input_map: InputMap<ControAction>
the trait `_IMPL_SAVEFILE_SERIALIZE_FOR_SaveData::_savefile::Serialize` is not implemented for `InputMap<ControlAction>`

# for input_map: Vec<KeyCode, ControlAction>
the trait `_IMPL_SAVEFILE_SERIALIZE_FOR_SaveData::_savefile::Serialize` is not implemented for `std::vec::Vec<(bevy::prelude::KeyCode, ControlAction)>`
the trait `WithSchema` is not implemented for `bevy::prelude::KeyCode`
```
Is saving external structs supported?

**Comment by avl** [comment]
Hello!

Thank you very much for getting in touch.

The problem you've run into is basically because of something usually referred to in rust as the "Orphan problem".

In short, a trait can only be implemented by

a) The crate which defined the trait
b) The crate which defined the type that implements the trait.

The Savefile-traits can therefore only be implemented by

a) Savefile itself
b) The crate which owns the type that is to be serialized

In your case, only Savefile itself or Bevy and leafwing_input_manager could implement them, not your crate.

There are (I think) five options:

a) Bevy decides to support Savefile, and adds 'Derive(Savefile)' to all structs. This is probably unlikely :-) .
b) Savefile gets (optional) Bevy-support. I would not be against merging PR:s for this, but I do not have the time to implement it myself. Bevy looks super cool, so I'd love to have first class support for it in savefile.
c) You wrap the bevy-objects in a wrapper type, and then implement the Savefile-traits for that wrapper.

Like this:
```rust

struct MyMap {
  input_map: InputMap<ControAction>
}

impl Serialize for MyMap {
 ... code 
}
... repeat for Deserialize, WithSchema and Introspect (if needed)


#[derive(Clone, Debug, Default, Savefile)]
struct ControllerConfig {
  input_map: MyMap
}
```

d) You avoid using bevy-objects entirely in your serialized data. Are you sure you want to tie your savefile format to Bevy's data structures? The answer may well be 'Yes'. If the answer is no, maybe you don't need to actually persist this input_map thing? n this case, you might get away with putting #[savefile_ignore] before 'input_map'. 

e) Savefile gains support for serializing external types through by allowing attributes to designate serialize/deserialize-functions.

So, as to the question at the end of your post: The answer is basically 'It depends'. Some external types are supported because Savefile ships with support for ArrayVec, BitVec, IndexMap and a few other useful types. Other external types are not possible to support, because of the Rust Orphan Rule.

The strategy I myself have used is to not put any types from the Game Engine itself in my game state. But I don't have experience with Bevy, it may be that for Bevy this is really hard to avoid?

Did this help you any? :-)

**Comment by avl** [comment]
The best way forward is probably to add explicit support for Bevy-datatypes to Savefile.

I would be willing to merge PR:s adding this.

But for now, I think the best I can offer is the advice to wrap any foreign types in own types, and manually implement the Savefile-traits for those local types.

With that, I'm closing this issue. Feel free to reopen!
